apiVersion: v1
kind: Service
metadata:
  name: queryservice-srv
spec:
  type: NodePort
  selector:
    app: queryservice
  ports:
    - name: queryservice
      protocol: TCP
      port: 80
      targetPort: 80