apiVersion: v1
kind: Service
metadata:
  name: transservice-srv
spec:
  type: NodePort
  selector:
    app: transservice
  ports:
    - name: transservice
      protocol: TCP
      port: 80
      targetPort: 80